"""
Nutrition Agent — rule-based scoring with LLM abstraction layer.

When ANTHROPIC_API_KEY is set, the summary is generated by Claude.
Otherwise, a rule-based summary is used as fallback.
The scoring logic is always deterministic (rule-based).
"""
from __future__ import annotations
import os
import logging
from ..models.product import Product, NutritionFacts
from ..models.analysis import (
    AnalysisResult, HealthVerdict, RiskLevel,
    DiabeticFlag, AllergenWarning, Alternative,
)

logger = logging.getLogger(__name__)

_ANTHROPIC_KEY = os.getenv("ANTHROPIC_API_KEY")


async def analyze(product: Product) -> AnalysisResult:
    n = product.nutrition
    score = _score(n)
    verdict = _verdict(score)
    diabetic = _diabetic_risk(n)
    highlights = _highlights(n)
    concerns = _concerns(n)
    summary = await _summary(product.name, verdict, highlights, concerns)

    return AnalysisResult(
        barcode=product.barcode,
        verdict=verdict,
        health_score=score,
        summary=summary,
        highlights=highlights,
        concerns=concerns,
        diabetic_flag=diabetic,
        allergen_warnings=[
            AllergenWarning(
                allergen=a,
                note=f"This product contains {a}. Avoid if allergic.",
            )
            for a in product.allergens
        ],
        alternatives=_alternatives(verdict),
    )


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

def _score(n: NutritionFacts) -> int:
    score = 100
    # Sugar penalty
    if n.sugar > 20:
        score -= 30
    elif n.sugar > 10:
        score -= 15
    elif n.sugar > 5:
        score -= 5
    # Saturated fat penalty
    if n.saturated_fat > 10:
        score -= 20
    elif n.saturated_fat > 5:
        score -= 15
    # Sodium penalty
    if n.sodium > 0.6:
        score -= 15
    # Empty calorie penalty: high sugar + zero protein + zero fiber = empty calories
    if n.sugar > 5 and n.protein == 0 and n.fiber == 0:
        score -= 20
    # Positive signals
    if n.fiber > 5:
        score += 10
    if n.protein > 10:
        score += 5
    # Calorie density penalty
    if n.calories > 450:
        score -= 10
    return max(0, min(100, score))


def _verdict(score: int) -> HealthVerdict:
    if score >= 85:
        return HealthVerdict.excellent
    if score >= 70:
        return HealthVerdict.good
    if score >= 50:
        return HealthVerdict.moderate
    if score >= 30:
        return HealthVerdict.poor
    return HealthVerdict.avoid


def _diabetic_risk(n: NutritionFacts) -> DiabeticFlag:
    if n.sugar > 30:
        return DiabeticFlag(
            risk=RiskLevel.high,
            explanation="Very high sugar content. Strongly avoid if you have diabetes.",
        )
    if n.sugar > 12:
        return DiabeticFlag(
            risk=RiskLevel.medium,
            explanation="Moderate sugar. Consume with caution if you have diabetes.",
        )
    if n.sugar > 5:
        return DiabeticFlag(
            risk=RiskLevel.low,
            explanation="Low-to-moderate sugar. Monitor portion size.",
        )
    return DiabeticFlag(
        risk=RiskLevel.none,
        explanation="Minimal sugar content. Generally safe for diabetics.",
    )


def _highlights(n: NutritionFacts) -> list[str]:
    h = []
    if n.protein >= 10:
        h.append(f"Good source of protein ({n.protein}g)")
    if n.fiber >= 5:
        h.append(f"High in dietary fiber ({n.fiber}g)")
    if n.sugar <= 5:
        h.append(f"Low in sugar ({n.sugar}g)")
    if n.saturated_fat <= 2:
        h.append("Low saturated fat")
    if n.sodium <= 0.1:
        h.append("Very low sodium")
    if not h:
        h.append("Check portion size for balanced consumption")
    return h


def _concerns(n: NutritionFacts) -> list[str]:
    c = []
    if n.sugar > 20:
        c.append(f"Very high sugar ({n.sugar}g per 100g)")
    if n.saturated_fat > 10:
        c.append(f"High saturated fat ({n.saturated_fat}g)")
    if n.sodium > 0.6:
        c.append(f"High sodium ({n.sodium}g) — risk for hypertension")
    if n.calories > 450:
        c.append(f"High calorie density ({n.calories} kcal)")
    return c


def _alternatives(verdict: HealthVerdict) -> list[Alternative]:
    if verdict in (HealthVerdict.excellent, HealthVerdict.good):
        return []
    return [
        Alternative(name="Whole grain alternatives", reason="Higher fiber, more balanced nutrition"),
        Alternative(name="Fresh fruit", reason="Natural sugars with vitamins and fiber"),
    ]


# ---------------------------------------------------------------------------
# Summary — LLM if key available, otherwise rule-based
# ---------------------------------------------------------------------------

async def _summary(
    name: str,
    verdict: HealthVerdict,
    highlights: list[str],
    concerns: list[str],
) -> str:
    if _ANTHROPIC_KEY:
        try:
            return await _llm_summary(name, verdict, highlights, concerns)
        except Exception as exc:
            logger.warning("LLM summary failed, falling back to rule-based: %s", exc)
    return _rule_summary(name, verdict)


def _rule_summary(name: str, verdict: HealthVerdict) -> str:
    messages = {
        HealthVerdict.excellent: f"{name} is an excellent choice with well-balanced nutrition.",
        HealthVerdict.good: f"{name} is a good choice for most people in moderate amounts.",
        HealthVerdict.moderate: f"{name} has some nutritional concerns. Consume occasionally.",
        HealthVerdict.poor: f"{name} has significant nutritional issues. Limit consumption.",
        HealthVerdict.avoid: f"{name} is not recommended for regular consumption.",
    }
    return messages[verdict]


async def _llm_summary(
    name: str,
    verdict: HealthVerdict,
    highlights: list[str],
    concerns: list[str],
) -> str:
    """
    Calls Claude API to generate a natural-language summary.
    Only reached when ANTHROPIC_API_KEY is set.
    """
    import anthropic  # imported lazily to avoid hard dependency

    highlights_text = "; ".join(highlights) if highlights else "none notable"
    concerns_text = "; ".join(concerns) if concerns else "none notable"

    prompt = (
        f"Write a concise 1-2 sentence nutrition summary for '{name}'. "
        f"Overall verdict: {verdict.value}. "
        f"Positive points: {highlights_text}. "
        f"Concerns: {concerns_text}. "
        f"Be factual, clear, and avoid medical advice."
    )

    client = anthropic.AsyncAnthropic(api_key=_ANTHROPIC_KEY)
    message = await client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=150,
        messages=[{"role": "user", "content": prompt}],
    )
    return message.content[0].text.strip()
